EKSCluster:
  Type: AWS::EKS::Cluster
  Properties:
    Name: !Ref EKSClusterName
    RoleArn:
      "Fn::GetAtt": ["EKSIAMRole", "Arn"]
    ResourcesVpcConfig:
      SecurityGroupIds:
      - !Ref ControlPlaneSecurityGroup
      SubnetIds:
      - !Ref PublicSubnet01
      - !Ref PublicSubnet02
      - !Ref PrivateSubnet01
      - !Ref PrivateSubnet02
  DependsOn: [EKSIAMRole, PublicSubnet01, PublicSubnet02, PrivateSubnet01, PrivateSubnet02, ControlPlaneSecurityGroup]
